# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YULDh2osCg79jvrsRAR2f51tJzOxNDI1
"""

import random

def roll_dice():
    return random.randint(1, 6)

def play_round(player1, player2, scores):
    print(f"\n{player1}'s turn...")
    roll1 = roll_dice()
    print(f"{player1} rolled: {roll1}")

    print(f"{player2}'s turn...")
    roll2 = roll_dice()
    print(f"{player2} rolled: {roll2}")

    if roll1 > roll2:
        print(f"{player1} wins the round!")
        scores[player1] += 1
    elif roll2 > roll1:
        print(f"{player2} wins the round!")
        scores[player2] += 1
    else:
        print("It's a tie!")

def main():
    print("🎲 Welcome to the Dice Game!")
    player1 = input("Enter name for Player 1: ")
    player2 = input("Enter name for Player 2 (or type 'Computer'): ")

    rounds = int(input("How many rounds do you want to play? "))
    scores = {player1: 0, player2: 0}

    for i in range(rounds):
        print(f"\n--- Round {i+1} ---")
        play_round(player1, player2, scores)

    print("\n🏁 Final Scores:")
    print(f"{player1}: {scores[player1]}")
    print(f"{player2}: {scores[player2]}")

    if scores[player1] > scores[player2]:
        print(f"🎉 {player1} wins the game!")
    elif scores[player2] > scores[player1]:
        print(f"🎉 {player2} wins the game!")
    else:
        print("It's a draw!")

if __name__ == "__main__":
    main()